### ISSUE TITLE
[FFmpeg plugin] segment fault if preset is set as 10 for 720p input or lower resolution input.

### ISSUE THREAD

**Issue by djie1** [intel/SVT-HEVC#87]
Try this command: 
ffmpeg -i <720p input>.264 -c:v libsvt_hevc -preset 10 -tune 1 -rc 0 -qp 31 output.265, make sure it's "preset 10" which is not valid for 720p input.

The backtrace is like below:
#0  0x00007ffff57de277 in raise () from /lib64/libc.so.6
#1  0x00007ffff57df968 in abort () from /lib64/libc.so.6
#2  0x00007ffff5820d37 in __libc_message () from /lib64/libc.so.6
#3  0x00007ffff5829499 in _int_free () from /lib64/libc.so.6
#4  0x00007ffff62936a7 in EbH265EncComponentDeInit (h265EncComponent=0x1fc4860) at /home/jerry/Projects/SVT/SVT-HEVC/Source/Lib/Codec/EbEncHandle.c:1602
#5  0x00007ffff62936db in EbDeinitHandle (h265EncComponent=0x1fc4860) at /home/jerry/Projects/SVT/SVT-HEVC/Source/Lib/Codec/EbEncHandle.c:1623
#6  0x0000000000433f5a in eb_enc_close (avctx=<optimized out>) at libavcodec/libsvt_hevc.c:391
#7  0x0000000000af2aa9 in avcodec_open2 (avctx=0x1f90680, codec=codec@entry=0x177baa0 <ff_libsvt_hevc_encoder>, options=options@entry=0x205cde0) at libavcodec/utils.c:1019
#8  0x00000000004a1358 in init_output_stream (ost=ost@entry=0x205cc80, error=error@entry=0x7fffffffcdd0 "", error_len=1024) at fftools/ffmpeg.c:3521
#9  0x00000000004a2fa6 in reap_filters (flush=flush@entry=0) at fftools/ffmpeg.c:1446
#10 0x00000000004a733a in transcode_step () at fftools/ffmpeg.c:4647
#11 transcode () at fftools/ffmpeg.c:4691
#12 0x0000000000485edd in main (argc=<optimized out>, argv=0x7fffffffdb58) at fftools/ffmpeg.c:4898

**Comment by djie1** [comment]
@jsunintel is following this issue.

**Comment by djie1** [comment]
The issue also happens for the following parameter combinations:
-	Preset 10 – Resolution < 1080p
-	Preset 11 – Resolution < 4k
-	Preset 12 – Resolution < 4k
